### ISSUE TITLE
Ars Magica 2 Compatibility?

### ISSUE THREAD

**Issue by Ra-Zim** [KaiKikuchi/ForgeRestrictor#15]
So I have not tried this yet, but with the mod Ars Magica 2, there is a spell called Dig that bypasses most anti-griefing options out there. Does this allow me to ensure that areas are protected from that? Or do you have that protected by default in your Grief Prevention Plus?

**Comment by KaiKikuchi** [comment]
Unfortunately, I think that Dig bypasses Forge Restrictor too, due to the way the spell has been developed is hard or even impossible to block it without modifying Ars Magica 2 code.

Anyway, I haven't tested it so I am not sure.

**Comment by spannerman79** [comment]
In all honesty any breaking or placing of blocks should be done with a fake player - for which AM2 *doesn't* do.

This isn't just an issue with GPP but also for even ForgeEssentials - no fake player no way to block it.  For that example see https://github.com/ForgeEssentials/ForgeEssentials/issues/855

**Comment by Ra-Zim** [comment]
Heh, I was so happy when I saw AM2 had been updated again finally, but this is a fan update I guess and it seems they removed whatever was done to make it not bypass claims and the like, I'll just make it only accessible by those well-trusted with the server.

**Comment by KaiKikuchi** [comment]
In this case, using a Fake Player is inappropriate. The block break/block place event should expose the player who did the action, not a fake player.

Fake players are use for TileEntities, because they are "machines" placed in the world that do something. The action are done by a TileEntity, not a player, so in that case it should use a FakePlayer.

The most annoying thing is that calling an event with or without a fake player is **VERY EASY**, and they don't do it.

**Comment by iKaneki-Ken** [comment]
The problem with it is Ars Magica 2's Dig spell doesn't trigger a block place/break event, already tried tracking it to no avail. It's breaking blocks in a way that not even Forge sees it and because all the player is doing is right clicking a block, it doesn't trigger Prism or any other action logging plugin.

**Comment by LemADEC** [comment]
The AM2 Dig spell does fire Forge events since at least September 2015.

**Comment by spannerman79** [comment]
@LemADEC AM2 dig spell should use the casters UUID.  Take for example how forestry uses the actual owner of the TE's UUID for checks.

**Comment by LemADEC** [comment]
AM2 uses the player itself when it's the caster, or create a custom player with a random UUID and that player name.

https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/spell/components/Dig.java#L81

https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/utility/DummyEntityPlayer.java#L24

Sadly, it doesn't use the base FakePlayer class nor reuse the original player UUID.
To my knowledge, the only real issue is with the caster block which anyways crashes in SMP.
