### ISSUE TITLE
[Suggestion] Make the ticks configurable

### ISSUE THREAD

**Issue by Bennyboy1695** [KaiKikuchi/ForgeRestrictor#7]
When an item has been set in the forgerestrictor plugin it only removes it for 3 ticks a time.
Would it be possible to add an argument to the command when you add which allows you to set a separate amount of time compared to default amount of ticks ?

**Comment by KaiKikuchi** [comment]
Is there any reason for this?

**Comment by Bennyboy1695** [comment]
Certain tools like the Botania Kings law key still can do there ranged affect while their item is confiscated every 3 ticks as it gives the player enough time to build up the affect.
Also 3 ticks seems to be hardly noticeable for players as i have had multiple players say that the tool just flickered but they didn't really notice it leave their inventory (This could be fixed by sending a message to the player saying their item was confiscated)

**Comment by KaiKikuchi** [comment]
To be honest, I don't think increasing ticks will help. At the first place it's modders fault for not using Forge events properly. The "confiscation" thing should "trick" the forge mod, but unfortunately it won't always work. Anyway, it's not hard to add that so I'll add it anyway.

**Comment by KaiKikuchi** [comment]
Added in v.1.3.4

**Comment by Bennyboy1695** [comment]
Thank you for adding this :) Only problem is theres no documentation on how to use it, and the ingame help doesn't tell you either

**Comment by iKaneki-Ken** [comment]
This won't fix anything if the Bukkit event isn't preventing the modded items action, doesn't matter how immediate the confiscation is, the moment it's right clicked, anything with an immediate reaction will be able to bypass this plugin.

In order to protect against instances like this, the server software has to hook into the API of the mod of the item in question, otherwise, this plugin won't be able to protect against items such as Mining Lasers or better yet Wrenches in general as the special right click function of the Wrench is do VIA custom packets which Bukkit doesn't account for.
